apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
    type: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: frontend
        ports:
          - containerPort: 80
